<a href="https://colab.research.google.com/github/SidElias/IDP-G11/blob/main/NLP_IDPG11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
from tensorflow import keras

from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences

In [2]:
import json

with open('MSASL_classes.json', 'r') as f:
    data = json.load(f)

In [26]:
vocab_size = 10000
embedding_dim = 16
max_length = 100
trunc_type='post'
padding_type='post'
oov_tok = "<OOV>"
training_size = 20000

In [29]:
training_sentences = data[0:training_size]
testing_sentences = data[training_size:]

In [30]:
tokenizer = Tokenizer(num_words=vocab_size, oov_token=oov_tok)
tokenizer.fit_on_texts(training_sentences)

In [31]:
word_index = tokenizer.word_index
sequences = tokenizer.texts_to_sequences(training_sentences)


In [32]:
print ('\nWord Index = {}'.format(word_index))


Word Index = {'<OOV>': 1, 'not': 2, 'up': 3, 'every': 4, 'school': 5, 'you': 6, 'all': 7, 'love': 8, 'year': 9, 'week': 10, 'morning': 11, 'hair': 12, 'last': 13, 'like': 14, 'good': 15, 'hearing': 16, 'how': 17, 'night': 18, 'me': 19, 'afternoon': 20, 'next': 21, 'i': 22, 'long': 23, 'take': 24, 'center': 25, 'south': 26, 'nice': 27, 'want': 28, 'friend': 29, 'student': 30, 'spring': 31, 'help': 32, 'understand': 33, 'day': 34, 'play': 35, 'sign': 36, 'go': 37, 'france': 38, 'know': 39, 'meet': 40, 'more': 41, 'hour': 42, 'many': 43, 'see': 44, 'freeze': 45, 'break': 46, 'africa': 47, 'month': 48, 'hard': 49, 'one': 50, 'america': 51, 'down': 52, 'autumn': 53, 'room': 54, 'get': 55, 'short': 56, 'language': 57, 'to': 58, 'copy': 59, 'look': 60, 'on': 61, 'in': 62, 'half': 63, 'come': 64, 'face': 65, 'that': 66, 'than': 67, 'hello': 68, 'teacher': 69, 'eat': 70, 'no': 71, 'happy': 72, 'orange': 73, 'deaf': 74, 'sister': 75, 'finish': 76, 'white': 77, 'bird': 78, 'what': 79, 'tired': 8

In [33]:
print ('\nSequences = {}'.format(sequences))


Sequences = [[68], [27], [69], [70], [71], [72], [14], [73], [28], [74], [5], [75], [76], [77], [78], [79], [80], [29], [81], [82], [83], [30], [84], [31], [15], [85], [86], [87], [88], [89], [90], [91], [92], [93], [94], [95], [96], [97], [98], [99], [100], [101], [102], [103], [104], [16], [105], [106], [107], [108], [32], [109], [110], [111], [112], [113], [114], [115], [116], [17], [33], [117], [118], [119], [120], [121], [122], [123], [6], [124], [125], [126], [34], [127], [128], [129], [130], [131], [132], [133], [134], [135], [136], [137], [138], [35], [36], [37], [139], [140], [141], [142], [143], [144], [145], [38], [146], [39], [147], [18], [148], [149], [150], [151], [152], [153], [154], [40], [155], [156], [157], [158], [19], [159], [2], [160], [161], [162], [163], [164], [165], [166], [167], [168], [169], [170], [171], [172], [173], [174], [175], [176], [177], [178], [7], [179], [180], [181], [182], [183], [184], [185], [186], [187], [188], [189], [190], [191], [192], [19

In [34]:
padded = pad_sequences(sequences, maxlen=max_length, padding=padding_type, truncating=trunc_type)
print ('\nPadded Sequences = {}'.format(padded))



Padded Sequences = [[ 68   0   0 ...   0   0   0]
 [ 27   0   0 ...   0   0   0]
 [ 69   0   0 ...   0   0   0]
 ...
 [974 975   0 ...   0   0   0]
 [976   0   0 ...   0   0   0]
 [977   0   0 ...   0   0   0]]


In [35]:
model = tf.keras.Sequential([
    tf.keras.layers.Embedding(vocab_size, embedding_dim, input_length=max_length),
    tf.keras.layers.GlobalAveragePooling1D(),
    tf.keras.layers.Dense(24, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])